### ISSUE TITLE
What type of noation would you like us to use in HW1 Question 4.a? Bold uppercase Z to represent a matrix, or write out the actual matrix in brackets?

### ISSUE THREAD

**Issue by marksorel8** [nwfsc-timeseries/atsa#3]

**Comment by amandawarlick** [comment]
I think matrix in brackets, since the uppercase y = Zx + e is for both forms 1 and 2. Not sure if @marksorel8 meant to reopen after he closed.

**Comment by amandawarlick** [comment]
Never mind, I think the full matrices is problem 4b.

**Comment by marksorel8** [comment]
Thanks, I think you are right. The closing and reopening was an "accident"...I wasn't sure I posted it in the right place and then decided I did. This is my first issue on GitHub!

**Comment by mdscheuerell** [comment]
@marksorel8 the key to issues is to write a short descriptive title, and then type the body of the Q/error/bug in the body. Note that you can use Markdown flavoring in issues so things like enclosing text in `` make it look like code (eg, `acf(x_data)`). You can also edit issues using the dropdown menu accessed via the "..." in the upper right next to the emoji/reaction link.
